import * as _ from 'lodash';
import { Request, Response, NextFunction } from 'express';
import { parseOffsetAndLimit } from '../../helpers/parser-utils';
import { Types } from 'mongoose';

// =============== GET ===============

export function parseGetByQuery(req: Request, res: Response, next: NextFunction) {
  const { query } = req;
  req.query = {
    ...parseOffsetAndLimit(query),
    find: {
      ...parseId(query),
    },
    ...parseSearch(query),
    ...parseQueryPopulate(query),
  };
  next();
}

export function parseGetMyProducts(req: Request, res: Response, next: NextFunction) {
  const { query } = req;
  req.query = {
    ...parseOffsetAndLimit(query),
    find: {
      ...parseId(query),
      ...parseUser(req.user),
    },
  };
  next();
}

function parseQueryPopulate({ populate }: any) {
  return populate ? { populate } : {};
}

function parseId({ _id }: { _id?: any }) {
  return _id ? { _id } : {};
}

function parseUser(user: any) {
    return user ? {user: Types.ObjectId(user._id)} : {};
}

function parseSearch({ keyword }: { keyword?: string }) {
  return keyword ? {
    or: [
        // { 'slug': { $regex: keyword, $options: 'i' } },
        // { 'title.en': { $regex: keyword, $options: 'i' } },
        // { 'title.ge': { $regex: keyword, $options: 'i' } },
        // { 'title.ru': { $regex: keyword, $options: 'i' } },
    ],
  } : {};
}

// =============== POST ===============

export function parseCreate(req: Request, res: Response, next: NextFunction) {
  req.body = parseBaseProps(req.body),
  next();
}

export function parseUpdate(req: Request, res: Response, next: NextFunction) {
  req.body = {
    _id: req.body._id,
    ...parseBaseProps(req.body)
  };
  next();
}

function parseBaseProps(body: any) {
  return _.pick(body, [
    'title',
    'description',
    'price',
    'price',
    'offerPrice',
    'priceWithAgreement',
    'images',
    'createDate',
    'canOfferPrice',
    'views',
    'adType',
    'condType',
    'youtubeUrl',
    'city',
    'category',
    'categorySlag',

    'accessoryType',
    'accumulator',
    'age',
    'airFiltrationSystem',
    'amountOfPrograms',
    'answeringSystem',
    'antibacterial',
    'artificial',
    'bagIncluded',
    'battery',
    'batteryCapacity',
    'bicycleType',
    'bitRate',
    'bluetoothHeadphones',
    'body',
    'brand',
    'bulletType',
    'butt',
    'calibre',
    'camera',
    'cameraType',
    'capacity',
    'cardSlot',
    'cassetteType',
    'catBreeds',
    'cdDvdReader',
    'changebleLen',
    'changer',
    'chargeType',
    'class',
    'color',
    'colors',
    'compatibleBrand',
    'compatibleLaptopSize',
    'componentsType',
    'computerType',
    'condition',
    'connectorType',
    'coolingType',
    'cover',
    'coverageArea',
    'dcVoltage',
    'decorative',
    'destined',
    'discType',
    'dispenser',
    'display',
    'displayTechnology',
    'displayType',
    'dogBreeds',
    'drawers',
    'dryingMode',
    'dubleBarrel',
    'electric',
    'electricityUsageClass',
    'energyClass',
    'energyType',
    'extensible',
    'extraMemoryIncluded',
    'eyeglassesType',
    'fax',
    'features',
    'fishSpecies',
    'fmRadio',
    'focalLength',
    'foldable',
    'forChildren',
    'forInterbreed',
    'form',
    'frame',
    'frameSize',
    'fromAuthor',
    'fruitSpecies',
    'fuelType',
    'galvanized',
    'gearType',
    'gender',
    'genre',
    'graphicsCardMemoryType',
    'graphicsCardProcessor',
    'handMade',
    'handmade',
    'hasOven',
    'headsetType',
    'heavyKey',
    'heel',
    'helmetSize',
    'hookahType',
    'instrument',
    'integratedSpeakers',
    'interface',
    'internalMemory',
    'inventoryType',
    'iseBox',
    'karaoke',
    'keyboardType',
    'laminated',
    'laminating',
    'language',
    'light',
    'lighting',
    'loadType',
    'loadingMechanizm',
    'loudspeaker',
    'lte4GNetwork',
    'manual',
    'material',
    'materialType',
    'maxSpeed',
    'mechanism',
    'mediaType',
    'memoryCard',
    'memoryRam',
    'memorySlot',
    'microcircuitType',
    'microphone',
    'microphoneIncluded',
    'mixingDough',
    'moistureRegulation',
    'multiColor',
    'nfc',
    'noFrost',
    'numberOfCameras',
    'numberOfSeats',
    'operatingSystem',
    'opticalDisck',
    'optics',
    'origin',
    'osVersion',
    'packingType',
    'paperType',
    'period',
    'phase',
    'power',
    'primaryCamera',
    'printingTechnology',
    'processorType',
    'ram',
    'ramCapacity',
    'ramType',
    'recorder',
    'recordingDefinition',
    'remoteControl',
    'resistorsType',
    'resolution',
    'screen',
    'screenSize',
    'screenType',
    'screenWidthMantle',
    'selectTheType',
    'selfieCamera',
    'serviceArea',
    'shockAbsorber',
    'shortMovie',
    'simCard',
    'simMultiple',
    'simSize',
    'size',
    'smartTv',
    'socket',
    'soft',
    'speedometer',
    'ssdCapacity',
    'ssdType',
    'steam',
    'stone',
    'stoneSurface',
    'storageType',
    'strings',
    'structure',
    'subject',
    'substance',
    'subwoofer',
    'surfaceMaterial',
    'systemType',
    'systemsType',
    'theTotalNumberOfLoudspeakers',
    'threeD',
    'threeGNetwork',
    'totalPixels',
    'touchScreen',
    'touchscreen',
    'transmitterType',
    'tripodIncluded',
    'twoStoried',
    'type',
    'typeOfAlcohol',
    'typeOfBoards',
    'typeOfBusiness',
    'typeOfConnectors',
    'typeOfDevice',
    'typeOfDiode',
    'typeOfFfowcharts',
    'typeOfFurniture',
    'typeOfFuses',
    'typeOfLed',
    'typeOfLight',
    'typeOfMaterials',
    'typeOfMeasuring',
    'typeOfOptocouplers',
    'typeOfRadiators',
    'typeOfSensors',
    'typeOfSolderingIron',
    'typeOfSwitches',
    'typeOfTools',
    'typeOfTransformers',
    'typeOfWires',
    'typeSpecialMachinery',
    'usb',
    'usbVersion',
    'vegetableSpecies',
    'vehicleType',
    'videocard',
    'viewingWindow',
    'voiceNavigation',
    'volume',
    'waterResistance',
    'wetCleaning',
    'wiFi',
    'wireless',
    'withBasin',
    'withBow',
    'withDrawerS',
    'withFlash',
    'withGas',
    'withHeadphone',
    'withLight',
    'withMemoryCards',
    'withMirror',
    'withScreen',
    'withSpringMattress',
    'year',
    'вreedOfRabbit',
  ]);
}
